# -*- coding: utf-8 -*-
"""Segunda Preentrega.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Eva5VU_FeSaqumo9zvuetqy_Zqld8-hT
"""

pip install openai==0.28

import openai
import textwrap

#pongo asi la apikey para protegerla
openai.api_key = os.getenv("OPENAI_API_KEY")

def generar_descripcion_mascota(nombre_marca, valores, sector, descripcion_empresa):
    prompt = f"""
    Eres un experto en diseño de marcas y creación de personajes icónicos.
    Genera una descripción breve y precisa para una mascota de marca con los siguientes criterios:

    - Nombre de la marca: {nombre_marca}
    - Valores de la marca: {valores}
    - Sector de la marca: {sector}
    - Descripción de la empresa: {descripcion_empresa}

    La descripción debe incluir:
    - Características físicas (ejemplo: criatura mitológica con cuerpo metálico azul y dorado)
    - Expresión y personalidad (ejemplo: imponente, majestuoso, protector, confiado)
    - Elementos distintivos (ojos brillantes, detalles tecnológicos, escudo futurista)

    La respuesta debe estar en español, ser clara y NO superar los 850 caracteres. Usa frases cortas y concisas.
    """

    response = openai.ChatCompletion.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": "Responde únicamente en español."},
            {"role": "user", "content": prompt}
        ],
        max_tokens=200
    )

    descripcion = response["choices"][0]["message"]["content"]


    descripcion_reducida = textwrap.shorten(descripcion, width=950, placeholder="...")

    return descripcion_reducida


nombre_marca = "Olimpo Web"
valores = "Lealtad, Innovación, Calidad"
sector = "Desarrollo de páginas web"
descripcion_empresa = "Creamos páginas web de alta calidad con tecnología de vanguardia."


descripcion_mascota = generar_descripcion_mascota(nombre_marca, valores, sector, descripcion_empresa)
print("\nDescripción Generada:\n", descripcion_mascota)

import openai
import textwrap

#pongo asi la apikey para protegerla
openai.api_key = os.getenv("OPENAI_API_KEY")


descripcion_mascota = """
 La mascota de Olimpo Web es "Calyx", un centauro cibernético de cuerpo metálico azul y dorado. Su apariencia es la de una majestuosa criatura mitológica, combinando tradición e innovación.
"""


def generar_imagen(descripcion):

    prompt_imagen = f"""
    Arte digital hiperrealista en calidad 8K.
    Personaje en estilo de videojuego AAA con texturas altamente detalladas.
    Iluminación cinematográfica, con contrastes dinámicos y reflejos en armaduras metálicas.
    León antropomórfico con armadura dorada brillante, detalles en azul neón y textura metálica pulida.
    Ojos de luz azul intenso, mirada majestuosa con expresión de inteligencia artificial avanzada.
    Alas holográficas de energía con circuitos bioluminiscentes.
    Fusión de mitología y tecnología: diseño biomecánico con inspiración futurista.
    Fondos épicos con iluminación de neón dorado, resaltando los contornos de la figura.
    No incluir texto, letras ni logotipos en la imagen.

    --- Descripción de la mascota ---
    {descripcion}
    """

    response = openai.Image.create(
        prompt=prompt_imagen,
        n=1,
        size="1024x1024"
    )

    return response["data"][0]["url"]

imagen_url = generar_imagen(descripcion_mascota)
print("\nImagen Generada:", imagen_url)

